version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:00"
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: "/dev-support/containers/debian"
    schedule:
      interval: "daily"
      time: "21:00"
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: "/dev-support/containers/alpine"
    schedule:
      interval: "daily"
      time: "21:00"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:00"
    open-pull-requests-limit: 10
