[package]
name = "tunelo"
version = "0.1.0"
authors = ["xrelkd <46590321+xrelkd@users.noreply.github.com>"]
edition = "2018"

default-run = "tunelo"
autobins = false

[features]
default = ["tunelo"]

app = ["toml", "structopt", "simple_logger", "serde_json"]

tunelo = ["app"]

[lib]
name = "tunelo"
path = "src/lib.rs"

[[bin]]
name = "tunelo"
path = "src/bin/main.rs"
required-features = ["app"]

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
trust-dns-resolver = "0.19"

snafu = "0.6"
structopt = { version = "0.3", optional = true }
url = "2"

serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
toml = { version = "0.5", optional = true }

byteorder = "1"
bytes = "0.5"

log = "0.4"
simple_logger = { version = "1", optional = true }

lru_time_cache = "0.10"
