unstable_features             = true

max_width                     = 100
newline_style                 = "Unix"
use_field_init_shorthand      = true
use_small_heuristics          = "Max"
use_try_shorthand             = true
wrap_comments                 = true
fn_single_line                = true
format_strings                = true
format_macro_matchers         = true
reorder_impl_items            = true
reorder_imports               = true
merge_imports                 = true
condense_wildcard_suffixes    = true
imports_layout                = "Mixed"
normalize_comments            = true
normalize_doc_attributes      = true
