[formatter.rust]
command = "cargo"
options = [
  "fmt",
  "--all",
  "--verbose",
  "--"
]
includes = [ "*.rs" ]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
  "*.yaml",
]

[formatter.nix]
command = "nixpkgs-fmt"
includes = [
  "*.nix"
]

[formatter.shell]
command = "sh"
options = [
    "-eucx",
    """
# Perform static analysis tool
shellcheck --external-sources --source-path=SCRIPTDIR "$@"

# Run formatter
shfmt --write --simplify --case-indent --indent 4 "$@"
    """,
    "--"
]
includes = ["*.sh"]
