name: "Nix Flakes"

on:
  push:
    branches:
      - ci/*
      - main
      - develop
      - release/*
  pull_request:
    paths:
      - Cargo.lock
      - Cargo.toml
      - default.nix
      - flake.lock
      - flake.nix
      - shell.nix

jobs:
  build-nix-flake:
    name: Build Nix Flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build Nix Flake
        run: nix build

      - name: Check Nix Flake
        run: nix flake check

      - name: Test Tunelo binary
        run: ./result/bin/tunelo version
