name: Rust

on:
  push:
    branches:
      - ci/*
      - main
      - develop
      - release/*
  pull_request:
    paths:
      - "src/**"
      - ".github/**"
      - Cargo.lock
      - Cargo.toml
      - deny.toml
      - rust-toolchain.toml
      - rustfmt.toml

env:
  CI: 1
  # Rust toolchain
  NIGHTLY_TOOLCHAIN: nightly-2023-03-25
  CARGO_TERM_COLOR: always
  CARGO_ARGS: --workspace --bins --examples --tests --benches --all-targets --all-features

concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rustfmt:
    name: Check Rust format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          override: true
          components: rustfmt

      - name: cargo fmt --version
        run: |
          cargo fmt --version

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --verbose --check

  udeps:
    name: Check unused dependencies
    runs-on: ubuntu-latest
    needs:
      - rustfmt
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Install dependencies
        run: |
          sudo ./dev-support/bin/install-deps

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          override: true
          components: rustfmt

      - name: Pre Cache
        run: |
          rm -rf ~/.cargo/registry/index/ ~/.cargo/registry/cache/ ~/.cargo/git/db/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo-udeps
        uses: aig787/cargo-udeps-action@v1
        with:
          version: latest
          args: ${{ env.CARGO_ARGS }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    needs:
      - rustfmt
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo ./dev-support/bin/install-deps

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          override: true
          components: clippy,rustfmt

      - name: Pre Cache
        run: |
          rm -rf ~/.cargo/registry/index/ ~/.cargo/registry/cache/ ~/.cargo/git/db/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo clippy --version
        run: |
          cargo clippy --version

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: ${{ env.CARGO_ARGS }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - clippy
      - udeps
    env:
      NEXTEST_RETRIES: 5
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
        mode:
          - release
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo ./dev-support/bin/install-deps

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain == 'nightly' && env.NIGHTLY_TOOLCHAIN || matrix.toolchain }}
          profile: minimal
          override: true
          components: rustfmt

      - name: Pre Cache
        run: |
          rm -rf ~/.cargo/registry/index/ ~/.cargo/registry/cache/ ~/.cargo/git/db/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install latest cargo-nextest release
        uses: taiki-e/install-action@nextest

      - name: Test with cargo-nextest
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --workspace --no-fail-fast ${{ matrix.mode == 'release' && '--release' || '' }}

  # miri:
  #   name: Miri
  #   runs-on: ubuntu-latest
  #   needs:
  #     - clippy
  #     - udeps
  #   env:
  #     CARGO_BUILD_RUSTC_WRAPPER: ""
  #     MIRIFLAGS: -Zmiri-symbolic-alignment-check
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       toolchain:
  #         - nightly
  #       mode:
  #         - release
  #   steps:
  #     - uses: actions/checkout@v3
  #
  #     - name: Install dependencies
  #       run: |
  #         sudo ./dev-support/bin/install-deps
  #
  #     - name: Install Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: ${{ matrix.toolchain == 'nightly' && env.NIGHTLY_TOOLCHAIN || matrix.toolchain }}
  #         override: true
  #         components: miri,rust-src,rustfmt
  #
  #     - name: Pre Cache
  #       run: |
  #         rm -rf ~/.cargo/registry/index/ ~/.cargo/registry/cache/ ~/.cargo/git/db/
  #
  #     - name: Cache
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  #
  #     - name: cargo miri --version
  #       run: |
  #         cargo miri setup
  #         cargo miri --version
  #
  #     - name: Run cargo miri
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: miri
  #         args: test --workspace --no-fail-fast ${{ matrix.mode == 'release' && '--release' || '' }} -- --nocapture
  #
  doc:
    name: Doc
    runs-on: ubuntu-latest
    needs:
      - clippy
      - udeps
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Install dependencies
        run: |
          sudo ./dev-support/bin/install-deps

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          override: true
          components: clippy,rustfmt

      - name: Pre Cache
        run: |
          rm -rf ~/.cargo/registry/index/ ~/.cargo/registry/cache/ ~/.cargo/git/db/

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps --bins --all-features
