name: Lines of code

on:
  push:
    branches:
      - ci/*
      - main
      - develop
      - release/*
  pull_request:

jobs:
  tokei:
    name: Tokei
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install nixpkgs-fmt
        run: nix profile install 'nixpkgs#tokei'

      - name: Run tokei
        id: tokei
        run: |
          ./dev-support/bin/lines-of-code
